name: minerz
description: "An app to learn about bitcoin with fun !"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.8.3
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2

flutter_launcher_icons:
  image_path: "icon/minerz_launcher_icon.jpg" 
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/medaille.png
    - images/btc_light.png
    - images/X.jpg
    - images/youtube.png
    - images/bell.png
    - images/handshake.png
    - images/calendar.png
    - images/nostr.png
    - images/2fingz.png
    - images/5fingz.png
    - images/10fingz.png
    - images/alien.png
    - images/satoshi_referal.jpeg


  fonts:
    - family: Rye # Numbers
      fonts:
        - asset: fonts/Rye-Regular.ttf
    - family: BungeeSpice # Title
      fonts:
        - asset: fonts/BungeeSpice-Regular.ttf
    - family: PatuaOne # Title
      fonts:
        - asset: fonts/PatuaOne-Regular.ttf
